# Download themes repo
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes

# import color scheme of choice
import = ["~/.config/alacritty/themes/themes/iterm.toml"]
# import = ["~/.config/alacritty/themes/themes/argonaut.toml"]
# import = ["~/.config/alacritty/themes/themes/ayu_dark.toml"]
# import = ["~/.config/alacritty/themes/themes/gnome_terminal.toml"]
# import = ["~/.config/alacritty/themes/themes/github_dark_colorblind.toml"]
# import = ["~/.config/alacritty/themes/themes/xterm.toml"]

[font]
size = 10
bold = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold" }
italic= { family = "CaskaydiaCove Nerd Font Mono", style = "Italic" }
bold_italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold Italic" }
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[colors]
draw_bold_text_with_bright_colors = true
cursor = { text = "CellBackground", cursor = "#ffffff" }

[cursor.style]
blinking = "Always"

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "L", mods = "Control|Shift", chars = "l" },
    { key = "V", mods = "Command", action = "Paste" },
    { key = "C", mods = "Command", action = "Copy" },
    { key = "Key0", mods = "Command", action = "ResetFontSize" },
    { key = "Equals", mods = "Command", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Command", action = "DecreaseFontSize" },
    { key = "N", mods = "Command", action = "SpawnNewInstance" },
]

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[scrolling]
history = 100000
multiplier = 10

[window]
dynamic_padding = false
opacity = 0.9
dynamic_title = true
# ligatures = true
padding = { x = 1, y = 1 }
