require "usman.options"
require "usman.keymaps"

require "usman.plugins-setup"
require "usman.colorscheme"
require "usman.autocompletion"
require "usman.treesitter"
require "usman.rainbow-delimiters"
require "usman.autopairs"
require "usman.comment"
require "usman.indent-blankline"
require "usman.gitsigns"
require "usman.nvim-tree"