require "usman.options"
require "usman.keymaps"

require "usman.plugins-setup"
require "usman.colorscheme"
require "usman.autocompletion"
require "usman.treesitter"
require "usman.rainbow_delimiters"
require "usman.autopairs"
require "usman.comment"